exclude: "node_modules|migrations|.git|.tox|flux-system|ios|android|charts|chart"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
          - json
          - yaml
          - markdown

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.0.3
    hooks:
      - id: forbid-secrets

  # throwing errors when eslint ran with npm/yarn doesn't...literally so fucking annoying.
  # comment out just in case solution in pre-commit is found before another framework is used.
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.5.0
  #   hooks:
  #     - id: eslint
  #       additional_dependencies:
  #         - "@typescript-eslint/eslint-plugin@^5.8.0"
  #         - "@typescript-eslint/parser@^5.8.0"
  #         - eslint@8.5.0
  #         - eslint-config-airbnb@19.0.4
  #         - eslint-config-airbnb-typescript@^16.1.0
  #         - eslint-config-prettier@^8.3.0
  #         - eslint-plugin-prettier@^4.0.0
  #         - eslint-plugin-jest@^25.3.0
  #         - eslint-plugin-jsx-a11y@^6.5.1
  #         - eslint-plugin-promise@^6.0.0
  #         - eslint-plugin-react@^7.28.0
  #         - eslint-plugin-react-hooks@^4.3.0
  #       files: \.[jt]sx?$
  #       types: [file]
