creation_rules:
  - path_regex: ./infra/.*.yaml
    pgp: 54161A454FF4A56DF8590237EDFA7D24E72A509E
  - path_regex: ./flux/.*.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: 38EB88ECBF8553D01E181F56FB7E08FAA3C4FF58
