creation_rules:
  - path_regex: ./infra/.*.yaml
    pgp: 3CB573B2BE41C4C5B9671855B61E7387809D1F74
  - path_regex: ./flux/.*.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
