apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailhog
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: mailhog
      version: '4.1.x'
      sourceRef:
        kind: HelmRepository
        name: mailhog
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hosts:
        - host: mail.dev.erickdang.com
          paths:
            - '/'
      tls:
        - hosts:
            - mail.dev.erickdang.com
          secretName: letsencrypt-mailhog
