apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailhog
  namespace: flux-system
spec:
  releaseName: mailhog
  targetNamespace: default
  interval: 5m
  chart:
    spec:
      chart: mailhog
      version: '4.1.x'
      sourceRef:
        kind: HelmRepository
        name: mailhog
        namespace: flux-system
      interval: 1m
  values:
    service:
      type: NodePort
      nodePort:
        http: 30001
