apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: '5.2.x'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 1m
  values:
    provider: azure
    domainFilters: erickdang.com
    txtPrefix: externaldns-
    azure:
      secretName: external-dns
      resourceGroup: Domains
