apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  releaseName: postgres
  targetNamespace: default
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '10.5.0'
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: postgres-credentials
      valuesKey: postgresqlPassword
      targetPath: postgresqlPassword
    - kind: Secret
      name: postgres-credentials
      valuesKey: postgresqlDatabase
      targetPath: postgresqlDatabase
    - kind: Secret
      name: postgres-credentials
      valuesKey: postgresqlUsername
      targetPath: postgresqlUsername
