apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '10.5.0'
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    postgresqlPassword: DNgobUNfyho6vwGLILH93ryo6EP6uFQqXpIbEWhPxyUilfyCB5O7cebQauF7tcBK
    postgresqlDatabase: workout
    postgresqlUsername: UJmrllANSDCBQQrZJQAsSVSCxOccqTjD
