apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  postgresqlPassword: ENC[AES256_GCM,data:h4IQQ7BODFhXw+TRH8CEOW1aDh925zyH/ew7YVdVYmIkvqidqQQdt7c99DSnc37ccT+cna4biOXJ6uPYniCTMA==,iv:ou8eucCBV8P0aZYxuByiBGEl9h1EjqPxo+BumcMyBgo=,tag:AsXKpGL9sV+6ef4Ry4vHiA==,type:str]
  postgresqlDatabase: ENC[AES256_GCM,data:dKxDoBn7iQ==,iv:xidkWVw/cN9XwAjsSyzzUf3wBTynat0FEZL4CVZga9U=,tag:Y0Qw4lxjcwZsxP/LuGNGew==,type:str]
  postgresqlUsername: ENC[AES256_GCM,data:9o1K0x2qdR1IHQT7bP+syFAxMP6wC/bxeYwzy8xZa04=,iv:QJd8rOMtSSUVgScqpz+Q0sUVeTp8w13U4/2/U7y/G9M=,tag:cZJkBwXOOT3e8JQPif2IVQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2021-07-08T15:01:46Z'
  mac: ENC[AES256_GCM,data:q5gz+9XLY1p78L98d83s+sCN+9/iiqZ5O2hwlc6SKtsUMkJ8JlxIHjCwOsjxIRba7+uUwx6kWQVRuMhnjDH5VPHTg3aZLFlRGEAUEpD/QZw7YotD2b4O4x1vJmH8ZjO/9Q4tlWvSvdIIge9G1rG9tBWrlXH0DO2m/YYjclwcCqg=,iv:S/WELmWlamhOtHeWDaLNxGxbFYwoJx0CwyFOupfb0+8=,tag:rFyl0a1f0d2lVoxwjgf/ow==,type:str]
  pgp:
    - created_at: '2021-07-08T15:01:45Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA6NT+vb4dPztAQ/+NWQTVT7aMnY9HFfvROSo619qRg5b6A4BmvZArjeR0kz3
        gQu8zmqgf73iPu8yvBMwNJyFNfW5TVVo9VeUtbtU15Q82V45MLIBr9bQ+Oe+GmgY
        Af+sW4dRP/Wq9KmGnBj/dmqOeK7TQzp/37Fmn3FKcWgcQsGPhYvq5Cr3uncSMI+j
        oAHmcRvk1mKLb/mjS8Z7jkit6BVbdy7Y/JKxykOkG3itLogLSekGgnqyB7dMAOs8
        mMZtAwK2JKfsNxOuWA6ZDFkZjaNMIjfJlgjFgIfxIJGs08qHEUcpcMRxb5pCLrtr
        UNI166H28qbdcGHL806FvhsOpPo86GStpFTS9O/NUaE2My1EBQ39k7Cg2C3Oqq1C
        odPG/CFXN9r2QOSM8+Syw1v1+CHcfLxGkD4WUEkCEhU471n3WBwaWmGDApLNzU+j
        CBzWTzahEujkriGUpcwn+QcTHS2+NHwvCxDX7h/JOJF4YPihMFUmeiJCA284r1FP
        aqSwpwkLzLiqMYdJrY2gZcfDdtLRroz34QEnlICwEnuvk7dqiAp82WHltA3C6puc
        0ytS+vlAL8ZexaCnypECYslubfFk040esghgF1duWGa4AK5Okd4sX1ghQ0IfyIKj
        e3SBEthlfpiRWnCiwjk77+0B6lXo3Jg9o6mxGpS7vyCR2ut0u2kvzSk6wffHgSvU
        ZgEJAhVWaF+EmnNh7QwVm6l1hPkeyWupSy4v1XAjnwnbgr6h8mo3dV64+/vDRTMe
        c7nrbYEndvRQCAL/W8EucGWsjscE5WIFaxlH3U7GQFj4G4X2Y/ujClvZX2yy+1ZL
        JCa94a9IuQ==
        =HlGG
        -----END PGP MESSAGE-----
      fp: 38EB88ECBF8553D01E181F56FB7E08FAA3C4FF58
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
