apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
stringData:
  postgresqlPassword: ENC[AES256_GCM,data:RQRM6A5Ma+Cw7yceStBQZcOK6sNM7GyvNnmHxnQFnvgbiL6Dj/eT+T6bq32nKm77GCbMCTayr6fi7QtP9qk/Bw==,iv:DxNlqObbUvgwSZG8egCDNSMlSJkcKDFllWsMgJXsqz4=,tag:ULDPfyj/B+SR1bO4oTFkeA==,type:str]
  postgresqlDatabase: ENC[AES256_GCM,data:THpyCOaNTw==,iv:JER+lkfpn81nzTAaw+DEFOuOXxPGU7Og3DqnRE3f4HE=,tag:lwnqlQQFNVfzaGyG4ajXsQ==,type:str]
  postgresqlUsername: ENC[AES256_GCM,data:NQ7vuDojuqqHYkMIw8B8yaat2Kw2mQ/xZzV3QLVq7VU=,iv:zOJwqiYIlyRPOBjB09j/m5pVMMC0xhsC/T1yF0UT5PA=,tag:Mp+FjSz8tDvAvJe4zuwnxg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2021-07-15T15:46:28Z'
  mac: ENC[AES256_GCM,data:dN3EyzB8YGvvjJ/JJygiri/3X+Z3N6OJZjxwrbVuU326r3pfvHHdPybVqaiFiNoQBGSij16xBNeOx3zpEdKCMbMElHbSVie/+qVgmMXhH3eus0Ji6c7Rg/LI/XLy++L4hVlGC5JdsQWCezJ8s7eXRSZnkNT3O/zW9wYw84AkVQk=,iv:dKbyfZYuGuozaTSK/5LTYiqARn+oVsQ08IiXHNF/K5g=,tag:5YcSdnOCxoNoQqcjN1EomQ==,type:str]
  pgp:
    - created_at: '2021-07-15T15:46:27Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0lsvhpSLVLLAQ//ZCMo/TcoXgLOE1acXLB/aP7BEB2rzVj6p85kF+2FUq46
        lAWhXa6JXgI9vcgFCthXt7/UO9r00GcGqZ9BJ88BECjRBM1hXlJPqJXBe9P7OPIT
        pw4dzfVLj58/edWpFQobooHtdZypKhh0/JXcZ23FvjaIA4LQ5iK/+XRE+xDRaxKu
        qSKBbfR7a2qjvxHX1gPBk98unwTpN01eilZqDmO1P84rEp9cCtjw/aaIx9DQMq3s
        p/67Qw8/AvCM2JJraIxfTt4IfKXmVxm0s8h+DiX5tYOzvhiabFN/V5jef0X2IiT1
        ISGOWYtcAZ1T92D75VGBA1usIngL5EiFVY7YYlUO6sKcFFA1NJ2ngi4FvUe2ULye
        po5n1BM+dGaC4ub8VUWc4/a+0EoDFMCIm3EgfgNCSHB1WPfpHpvrfs3/IKn0QtZd
        9HGQ4Zobu71LuL+p9choC8wCJrBeYTBsfprTFuk+Pl8ZizMd76QQ7sYWz2YaqEBv
        nNK6VR2Q0T76/J7a2kYHBztvKJ6kGIMIJa0l8W04ZMTLJyBCM2bXE/bfK5ExGfS+
        VMQ5P5aUXCHRVVyhwnLC8vzdbqo70nzqKak87bdPplT4AqBaeSahIRBsU1QvW2Nj
        moxX1PRnGwRX9eaCV10elRkFgl4+HxfSaNERdOp/enI4JU+Sv4JO+2wFK09oJIzS
        XgGzh+VyTfjoCHd3y85aj8v/1nWe8asNUEvXIntxCaM9Q51yw5Lh0nx5BgZunAAJ
        pvJ7T8o7MxefpuEQGlhE2mxNQyUov0jFnDcnP2HALMB8rkmOQkaoX6rNzLa1wfM=
        =ZEmO
        -----END PGP MESSAGE-----
      fp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
