apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres-db
spec:
  type: ExternalName
  externalName: tracker-dev.postgres.database.azure.com
  selector:
    app: postgres-db
status:
  loadBalancer: {}
