apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: tracker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tracker
  filterTags:
    pattern: '^dev-[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
