apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.4.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true
