apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tracker
  namespace: default
spec:
  postRenderers:
    - kustomize:
        images:
          - name: ericdang/tracker
            newName: ericdang/tracker
            newTag: staging-c3360224-1626831912 # {"$imagepolicy": "flux-system:tracker:tag"}
