apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tracker
  namespace: default
spec:
  values:
    ingress:
      hosts:
        - host: dev.erickdang.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dev.erickdang.com
          secretName: letsencrypt-tracker
  postRenderers:
    - kustomize:
        images:
          - name: ericdang/tracker
            newName: ericdang/tracker
            newTag: dev-0aec147a-1632089553 # {"$imagepolicy": "flux-system:tracker:tag"}
