# apiVersion: v1
# kind: Secret
# metadata:
#   name: tracker-secrets
#   namespace: default
# type: Opaque
# stringData:
#   DJANGO_SETTINGS_MODULE: ENC[AES256_GCM,data:C8VRYdcwgyoRKnBgO6Rok91wNA==,iv:y5Zn/s/vRgRUCFZQsjmJSD2+jAamzct4WYxCXVNGleQ=,tag:2dVI2K87jlED+TyM52/zZg==,type:str]
#   DJANGO_SECRET_KEY: ENC[AES256_GCM,data:1ybA/nTFRAWDQbKuC1rdyl1uFlI3cTQ3y5noFHO9rYefB3VY+EE9UiTyMPiZdUXXLIbATxJGx9HigDxmKqFDtg==,iv:6Ep/7YldoUYmVzcQf2JFw8Np3NtVQcxhKr7B7ppKU5c=,tag:LrLMXBbnMqMA7m7J96dcqQ==,type:str]
#   DATABASE_URL: ENC[AES256_GCM,data:WfwT3RQ7AK0Hs6WiLuOh3VqIVBsvTLkTU4/M54slo02AiDSSwIiAbJLBW3MuSziYBX5z+beHqoo98+caNiJsb1GrfpLKnSJKg71m3D2v+3oeUZklxN08Wb6dmVK4G9aY5nDiEtquN8t0ZseoHWareGlutvIX5T4PQBRHe96P0vjc,iv:9x0zx1y7VWf3tXPApxoc39RzjDYy7WVg0iBzk7yKz7Y=,tag:LCzoshsuRErYiYl3nugTBg==,type:str]
# sops:
#   kms: []
#   gcp_kms: []
#   azure_kv:
#     - vault_url: https://flux-dev-b4bcd66564.vault.azure.net
#       name: tracker-sops
#       version: 48a5df9a35584e8a87780f9ff63e77bf
#       created_at: '2021-11-09T16:59:51Z'
#       enc: RhEcKIcXzsRkkjJhNfj1gJRvOPdp2AB6_yqG9eJltPwafB9T1yy_hjCIk0Nn698hMU_S8XCS9tQS7eLgShfd_3tCu_2ABGvC205uQldcCi-PCGiPA-WbcHAq5BLIZYGhy2vTdKyWz8j6lOzm1ShJmHyhJ_zKR2qGY4ndAsMMMxTKN7FNWFxtvpy0AR2-IV35SjMwzhQfzYw3GfwQHEDV3VRHJM4uGEjZHGXhLRR523WjzNvDMhmppxVSxz16dfSOKxbsuUw0N_dqsLkprBMsXxcguvDpztJrsIqFhnWuL1Uw7gUPIgr84OV0LnB4utbvxdFAD3dkQC7hiRuaZiC65A
#   hc_vault: []
#   age: []
#   lastmodified: '2021-11-09T16:59:53Z'
#   mac: ENC[AES256_GCM,data:vy6q5n29cOIhvP5ZFYmjqX7CAaBEcSPnG5lic/iMCCp1gF0qwPwoO3LLzWHcLlQeLnL+uIlhr4Us4PED3rCtKX1KF53Dn5JyyVbnwAlGLHYzgkbBEuJ3X56kYGeT5+UkPceQfmyLMnHRVp0ht3aG57xSx+7RV6kBmVoL+5uIFW0=,iv:foiwCgfPq91UNYUtVNF4Z2ecLpO8BXHeZyq73MafZ/Q=,tag:+r22M6ez4kKiuHsAEHrjQg==,type:str]
#   pgp:
#     - created_at: '2021-11-09T16:59:51Z'
#       enc: |
#         -----BEGIN PGP MESSAGE-----

#         hQIMA0lsvhpSLVLLAQ//Q85PVF47ZKOIsutLGlLgYp5Xr+3mv76CUTFshZQoZEXE
#         sFv8RyJsxmecYp7cUJngHjwQiQlU9r8IeTwE7FKmvjYoKij1NqRacg4ypUnsH2Tm
#         Ds322XrL5pcbRX8scVaEZ8UIDRB4k5/dy/a6SLQjzOKEyA1JG0aZZrcZ6nz4VlOE
#         7xl9xSA4LL1r69GKXUU6fW8/v65Z2cxdaRjEsFcAD+HQieP+UzM7KUYPAwGdbLmo
#         q/z6mjTeIMJxEA90kYoJanjetbSu3lH+X3gJGGs96+aOu4o7bJjIMTG90TkeiK7d
#         uZRwa3tpHvcnImLQRUtQScYr9M0DLZhXP7gNnXFOEN7KQfxCVhanJRUrjErLUzEt
#         O3SllPRwaGkm6UoqHPULxmxzMdxdzfuF0phNTyTmfkscQE2phYtSqa/kQmZWf6v7
#         pnhunM4TTmn9atxnKaKg/KB4hcpcPK26d/69Y5FhD1yT4BSYh2RI7RiBI4T/fZ6n
#         ciAdUMNpeyigquzFWlB41uG15bbgBHqLW7o2OCb51dDuJ9nMwfZrEyEcfjdi9Zlx
#         7LQ9JqTXpSQR+sI/Z+M0gXkVeId6rO6qEe8nQMoVUt+NReXglWK1sK4POmoepUpg
#         LtA8tu/yPzshpADXoMLQbr/Vh1WeIDZbxuhouWLFkIH+iMebzVzm+7DN4kJHhFHS
#         XgHA8qJGyVwMLNmdEMhWDXoq4r0eXppYr+YnwnJLy9xG8s21wi0DM9jpOj+xgZSb
#         emDsJqB/F82gVpcJlZKJ7zvbdtppmSAZ4jsMIlfy4tmkdt3+q7XRaQjXK7Phmug=
#         =xRct
#         -----END PGP MESSAGE-----
#       fp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
#   encrypted_regex: ^(data|stringData)$
#   version: 3.7.1
