apiVersion: v1
kind: Secret
metadata:
  name: tracker-secrets
type: Opaque
stringData:
  DJANGO_SETTINGS_MODULE: ENC[AES256_GCM,data:KprAd9nJncUMEhei+UFo6zL45A==,iv:NvGVFHk8hrd1+VnFxRWskr38/IeUm7hwkrX+Sulb7YA=,tag:Kl1M6wEO5DB6JYMruRDkrw==,type:str]
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:VQ7wY8VAYfAnGAIW9Cxc05IeYBXgJ0ZMgXKRlGU6bAozn88fnoRFVDpSIBtYkQKw7Sjt+vfFZ+oDpiruA1dUVw==,iv:YdWAX5zvvvwH1XnUHdAAop8u7QII/TniXbDZHeR+Ixk=,tag:r3jHzbpk2qJDDz4G6Vex/Q==,type:str]
  DATABASE_TYPE: ENC[AES256_GCM,data:3VygA5Ip/PQ=,iv:IctTKOekPJwdw6/ieRJeqPd6lzfDDJhv8QShpqIZ3SI=,tag:/iBLq5MQ58as2mGiJeuIYg==,type:str]
  DATABASE_HOST: ENC[AES256_GCM,data:5fs82YxY2n+5XllXdz649iKIun6Ip4uY5YcmiW08OcYyyOWb9WOHfYn4JaN8,iv:TbuZfAWbgvY+5vLscikF9OOr2CDCgJfdRoRxW6c/umI=,tag:HbibsZwegHgvNUIqKPsTxA==,type:str]
  DATABASE_PORT: ENC[AES256_GCM,data:Obji0g==,iv:R16PDTMUktAHa4hhR3+8Y7ncO6ImEWIO/0FdasvzCos=,tag:l1cNwijYYldtCbvrnO+N0A==,type:int]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:GW3xLUBOfZFVjXwYAZId5DoMDKfR4GtZF5qRkaFn8YezFlcQDcDm9+MFGvFG+++uNy73gxBPSHiM2/Ngx8hReg==,iv:epWybLpa0TJ4VG5CZtjXSgshAZ7fGxYqXF8uDEVnOIE=,tag:TtZWCiQLXXVnfeEwYorJvQ==,type:str]
  DATABASE_NAME: ENC[AES256_GCM,data:hkbyjBZNqw==,iv:AiIESaGsajlqc4uemA5C0LDfntmef06R5mR3AP3SyWI=,tag:zvJwI7OmZyG3ug67euLxzg==,type:str]
  DATABASE_USER: ENC[AES256_GCM,data:mdDTQrMB081rAl30Q0xng79vs9Jt1SmffmlyR+En3Mo=,iv:8eoBJg2M7m/jlqdbqNHJZ1+p20MmxseyIpqpeAFDlBI=,tag:HTCQoEShL3FWlDrqLw8ijA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:MCqNudpuCDqFu8kurw/WxqeJWD9mjEN6EcBNG2A6dKFD0tVRFOvZRs8aggDyOaKqcf2nEU3IhAVQtaxloplAzGi0hR8k+BZoKNnTuw9JrN/bvOoBJD123/L0laImzWpqw9teswtRp+De7Cc=,iv:/kgccvXe1mU1lh0dKL8fcF1efqCRCShl4A6DA9PKd7M=,tag:a5gRYEh/Emb5oBylwvovig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2021-07-09T15:37:27Z'
  mac: ENC[AES256_GCM,data:dD0CyuvxDvjd7FTemQN9qrhKJSx4JT0TjbBI8hT6tlp8anr/uJjEbgdQ+yiLWWQST/7ht9rKikps5Jh1RRkps6K0NK3c/H61ATvcQ5AsGnPN4yOn2pRUrpLMkgpq3l5LEzDt4Ih1NJEbgeUgWowA0ePML/JHXQaVtjxCD7o+mMQ=,iv:kZerj/mBB850H08d64/hVlGYtNLSvVtlm5L3SolQans=,tag:6IHz2h9Yd6v6zFyK4Q9Rew==,type:str]
  pgp:
    - created_at: '2021-07-09T15:37:26Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA6NT+vb4dPztAQ//ftpaNzQuskIIdrUR2WfOqvOEu34PMR+HRZ0FycDvpTgN
        B+RRkD4bLxUblH9Sen9+ucLnh+YABmRZvNrCt4iIhzeYasJZkyMxmEBVEKcFIAwc
        nF9J5eZ8oraT3UrsHXH0sk+2/Ps64hw4m1aDabhtiIrriUj0JV0NCUUuRlYIK4ud
        jy/jTegzKf7t8A31mU0S7Eclc2zvU0idOhq45IjMbyaz8axTezN1JosJZVkqbMrR
        6l+OadnOqtUZejNRSUBLS/bvSktsAiqeUeHl0E7mNwgVGwQjDQ340MSnJo2eP/jM
        EhsNa/cxwH/F1bMulLRHCWgWaLqOCngqMnGVpglK7lpl4yZ8eNgT6+7tXnpF97h/
        T9JIPxF2UmqklYCfmvLefDSYGMM3MWsqfWiOgl4gE0LuvRlVVQ7uu2T7ZFQYYLWM
        VBha6cNQJuOJToAQEsywU6gaEPgoi5YIx8jYZLr0N9CXj/XucnNVKwyXwlsqJr8L
        Q8Nywhe99Zbhf9zuFA3stgDiwONChtG9DZnyM2STF0xCH2IuT56r2r+hCsFUiIda
        an1iD6Xfgpzx/QB71AcQMOnMERzt5v2q+5hZ7IWWXyMRC66zR1LB+LCYmcERA36x
        UwUjH3YEjarZ43Cy+1u7iiW+LcrIK+W3H3mnZczV7WDt9AOUdJCOcJHGE8SgAOvU
        aAEJAhXCnTF3xQvX9AK0YEfuFbA7zpWlUuWMAwdSp8zCYLifGgOr5HkXVc26HdG1
        OE1Jq5sXaBD1MXZcA4Ro8pitu8JKIdlPUngb36ZPz4/tnyvYkcckv0uip2LSHzU7
        yDemL3Xzn/5V
        =yxt6
        -----END PGP MESSAGE-----
      fp: 38EB88ECBF8553D01E181F56FB7E08FAA3C4FF58
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
