apiVersion: v1
kind: Secret
metadata:
  name: tracker-secrets
  namespace: default
type: Opaque
stringData:
  DJANGO_SETTINGS_MODULE: ENC[AES256_GCM,data:yiHwnu+crcOY3KXB/TH7trpK0A==,iv:6x/U6eYL8g69qsEPFV23wAGaj2eDQEK0XJCssU5hdn4=,tag:FuGk1XKvbqrNnGSGNWlWDQ==,type:str]
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:yLSffXiDN4swUIJ7a5vzLYjHfZRtmv0+1rIiex6s9yQZQqKdGtyb7yXzUvlQO6IIOldKU51WWWEnifZtyk/jig==,iv:7Dbvq7Vp5dS6iKyeN/YYSQoH/PztPHuFNQQsqcxw5Jc=,tag:i6hvdmDuIYYlezxZA0XIPw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:CszgSAC4NgFu3h4uL2doynvnN567tAMxGj6EGsqPPzsXPbCveaMzTr138CrFVgniUjfeOYJO1qsUAvBBAUJ4XG7oG+Ck0dnca15RAjDDiBIslUHkrrCpt8ccLlxyD1QlnvYnfzLRqePaxkgHTJsl2nJlA86wN6AlS/muAmpJSROBczoPgHy8+5ggIOroJKMwLVEU4pbhQY6JPD8Uugj8GUnUtYVqD+c=,iv:s03iMN9NrnoSX8VkmcuIh7Zfip8Fjzb7ySNc4kpqMV8=,tag:xmpV0zBnAkJqKlaSLntf5Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2021-07-15T15:47:11Z'
  mac: ENC[AES256_GCM,data:5B2fKgtZrXzw22rA+tPsSrlIBFlFDAbBryohTaL6/mun8Wv7/pugqnGRFKXjBaqyxzQPixBxhBt8Mbvk6Kr5AvzRt3qz+LL47QEp02L+KVyhfrkPX+gT5haDACCQQTfWcxMpJoZClproSpXBaPhaXaBxibfhOyfsYLzLWshTocA=,iv:ZgVkgZ8KcxUCj4oE0m4cxj+Z0LkXeoSdY2rISpmxtgU=,tag:ytHHOVVoJBqWLiRBNjjZ9Q==,type:str]
  pgp:
    - created_at: '2021-07-15T15:47:11Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0lsvhpSLVLLAQ//cL+HD4E7uTPcA4jFbcrODJJMpYXhsxoaAy9K2pVv2JDd
        NAKSCiZudAOumTlqDZl22lFvHHgTpDgEDJIHRySmi/EVdGPN/mwyh6JBCSRzUMXl
        wouPd83Sqd1LGN06ZdC9OXm0TlOEu1uYqV6k2pFnM4NR2VC0zG3Waujc3Mowxr97
        bPFSSlcqYyr3qFSVDMKp8N7PhOiU/EoMgkcDzlUo0wAljOYONKNW2fqBzKwH5SIq
        3QInx5e3Et0SWFh+Bf5nPr4cT4o1Iws4b1JvMhbNsyVTxl1BgmZKqqHhMJ4gD+EK
        H+TM+nSB+AZK6oqi/QQNpx307sl1XGS2dCvlCEQVcIRXOBAZQrXYv0yp+9yDT5hP
        OMYSeXUGfGSK9/a4oHB1eZcTZJv7e8OFfMFcvd7IwcgFx+YjZmw/k7SS05PNfQ4Q
        n4sRRPm457A8DJ0/wdjvfnyIgQ03MERvl9ylt5cl/zkN2V9ObOUSpwC8Z4CRM1Uc
        kBs1pZH2jVyfdDb+FI9n+g/S6Psf1aHd1Dy+dALMSpBMc0KNpcEa9WqxfD2fxuEJ
        9SZlbaJGVio/8ERw/p7mupR9WKTMDNaBL2Nv00+EtYgkbxQZgbxHB6kj+wvmkGvx
        mcRQ+ejpGbFU6VLX3YbF/ObCe8XiFmJGPV+zPA/fy74PrAiaeTczQTA1jTKcDUnS
        XgFJ8sZ3TfAZrkUQg42997TC8Mv2XpIBPbxANorAGqGmb4fk17poXOAHV5BLSV85
        4Dbp0SV3eiwDlSpTTRYyhehcPXXdN7cHPgfrAU47IV7pEq8XWhtNF/2rAagydFg=
        =CgjV
        -----END PGP MESSAGE-----
      fp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
