apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: auth-chart
  secretRef:
    name: flux-system
  url: ssh://git@github.com/e-dang/App.git
  ignore: |
    /*
    !/flux
    !/**/chart
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: auth-chart
    commit:
      author:
        email: fluxcdbot@dne.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: auth-chart
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: flux/apps/dev
    strategy: Setters
