apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auth
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/auth
      version: '0.1.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
