apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka
      version: '14.2.x'
      sourceRef:
        kind: HelmRepository
        name: kafka
        namespace: flux-system
      interval: 1m
  values:
    installCRDs: true
