apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: external-dns
type: Opaque
stringData:
  azure.json: ENC[AES256_GCM,data:6BzLC1qGQMv5ZBti32UQ/+hNXMZUs+B30BGSqSP/eIFyuoZpwOzBujM/UGXkciyveZdto32ybXVFY1HetIvynaIaJMnWNGXPCn6U/POa51k8H4Z52pWEPt+YjVjKRM63QsOp/5abm7WArKvDoyArNItTq/iG2cdBP0YQHF80B78ivedoal9pFR3SGsj3Ai6HO/NhejKhyWV9a/I7l71Z1Fap/Oh0QjsMJVemF5rslQV2JlROUV4AmrXVWKp8KZ8krqWdFt0ApM8aahlfsK4DsanKRudJ5mo4d0hhdqCeq7NTZHPczDecpHZBDz0p/mxbVg8FgNYAvb76Q/ZaC78VR6LJdOoDBOU=,iv:elKi+bbX44yktYJCd/KIk4mKGUhi7Hgj/ZZTrpPLm5k=,tag:8ct6tNoWxViqg5lWiJKF+g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv:
    - vault_url: https://dev-df9335ce19e9bea0.vault.azure.net
      name: tracker-sops
      version: 6c40b271f7bd4fbebb4f906e1f3abe68
      created_at: '2021-10-17T23:54:25Z'
      enc: p6gmhIBAQIPe9sfMPPpbWZgPlYnllb3l6MaCxZlHNHmExi_4_ydgUl94hTwC5_rpNWt-8TiD-QXmK-VZDRFPfev5mIxZ_5ej6pq4Yk6iXDzz2VJDUpxk5ghrMpW9bErRS0yHFHjkVo_yBQSpRgpU5dIm0OEmWLFZ8by1ZQE_XeI35v-dv1bJW_e1yfM4DbLb-JOKZ3tSqFUU3UpxMp5_2Yipa9YK1snQLu046aeseZxKehnfhivltzjI0SlSyC5vmRW2GDyGE3HuErcrCco36Ho0v25xuQ-OfEXn1lM_5ayPMPkQOIfjZanoEo25-LtROjcpiPWBqdnGKLRJzmg_mQ
  hc_vault: []
  age: []
  lastmodified: '2021-10-17T23:54:30Z'
  mac: ENC[AES256_GCM,data:IanzyDyf89uydZLjhYa6tEyPkj4TRDvb28mootZoIWbxxJt9RxffbX6Ud04wKFNrfG+axMkOTR+IWNDlHXS1HNLTFuGqffCaVpoTXQTZAOALvVMBApVJtsXeXa0iy4zE75EJ4s/tugh8pqtYB9YfSyIEUw1iZZ4alJnfUlM4ZWg=,iv:ZtMtdTL7c+6OeNoEtdjgcS2WBe5R8Z1KIOgzPtatbfA=,tag:zYLdW2atlk920/PuB0qB0w==,type:str]
  pgp:
    - created_at: '2021-10-17T23:54:25Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0lsvhpSLVLLAQ/+IXUdvrUtr5S4Btn/Y2arforkL1m78alHO2YK27ZDDtD1
        PH/oiXvWIhSr+PYYZz0AGXjBN/J0PlQYMzLJdm96wmsGLrfmGQpgRt+s5NeI5UCi
        46BGvTfmT/GO0mYyXHnw6prKwRa0jCTY6LBKAAlyR4WpqJVzembvXqodsqj5Xbmb
        44e5IssiJXbzihv9SiN7hHZSioQqZIk99oBTOKzfgSDgRH4t0Du8KL9ZM1zM9NiN
        9yqWjsZrEGdE7INzd2QshKfdZUbcHqkkyDa/ri0QYdAob3R+lBY+1dl+RU3tBbtP
        7f1f1lrNtWcY2VNRUA7JW6rhXLcQmryfNV1TTTor7mX0NOq+OYUhYvn/ZLe4hlMO
        mKl1Kf69CptKR3fJnzXrIhlpTkDNFNzQTzybZWaJCIiwFzyWJ1QY3c9qPO+Rk1qo
        rP01JSpWXmxUjTC27Sit7SJXnsxaLzaP0Se4ngXAXAvoomLVU61eLKklnEO1xNh4
        z1mbA1Xgoyr7c92sufYWX0GwjclMSxdA0s9tNHPlp9xnV7s0v60jTRjMae+wOZ1M
        V5SbkZdJydqCl0VDZzPsRjw/K7OrK9HQcd3PL19TKoB5ykfHcFOTxnZWhT4hbIUW
        0AqMMljudxhK5qoeVvbxgJtWB6RdS9a4m92wgZ98FQ7aBqI1QaL3e/r2ug5/Q/bS
        XgG970xREkDLDkXZAsdsrk3WKyREp5P30arB/qO6sQHAm9t+I59dGo5VGtWLjq3s
        QhCo2IjUj6xZDAdgP8XYo+0eAhVt3D94fdE5dA2inA9srRpmsDnc1smPqbHhwwY=
        =tPp5
        -----END PGP MESSAGE-----
      fp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
