apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: external-dns
type: Opaque
stringData:
  azure.json: ENC[AES256_GCM,data:7Mv0yUXBpzHdtr2X+uRVl4IqtQplFBjfon3OutaCfGkEau0cEEQnrnduaKJurxvnVQqdxtP+869gkG0n6HoQfaKSvt9PoR6GPnBcDK+0bb+BxflJ/LWFml2CJMnORcQPGu+7VlD1rxxgOGpkVUoyEnewn+61M7jKRsB7opB0wMNnqncTdtNUWgN0xmLo3M/7O7aWw4hBBXI02DNwfd4Le/3mUueOkOeQt9+7u6YLsQNF5a1CHJfyEXsLOJRQE9OapyOkG/UthEwrXHm3A6swPEGDpZHZ2lepjVCZjtnht2PVTg15LwU9tsZGyVhLTkd9qv89RSffku4UIougKJUjjdD2gxJKsFI=,iv:nP3EZrXNGtWn/fg6EWaQZxY17w5uSZWrXIs45AGNoM4=,tag:0ghkcoWP85fGO9dul2V4bw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv:
    - vault_url: https://flux-dev-b4bcd66564.vault.azure.net
      name: external-dns-sops
      version: 4b084cc5367a42f88367fd1b1a5cc995
      created_at: '2021-10-31T00:32:08Z'
      enc: PKzFYXcncEjplwoLtGF5lDcJA6VUhFnMegDUa-NX0Qxsh7Q7eJhztmLTuV9e9HM0uF7EbXuZ4v7HEPVUVN6trBfgVwTrrsuNamkyj7mhiLLcl1pozL6D4FyUuGdD9F3lKP4C7_JZdYwcx2Xup5Zk5f0oGCnauTVpavZx2lf85ImfVD5FluQosp499-1ofwDWmsSrce7Rq2CIOvDeDiNBlsbmMmEDjrkEqeNJJZsBadDUecq1WSSMlaHPyLGwJpfloY7BdL0eWtrgWe31nPoh7Ok0-olTDkA-n5GAztRHVOkVytdLUfAVJIySZKI-hhWzsodbAM0gRn_CL49XzGBULQ
  hc_vault: []
  age: []
  lastmodified: '2021-10-31T00:32:12Z'
  mac: ENC[AES256_GCM,data:YekoNTjiWcarGC+55AvM/44FOSnZa5O2sZMXVBXaSTmw4A75DRH+99MiHsuOkeWAQRRAtMekjHqqVbM3PtP8KC0+fExWZpfvkEz8bdciayqu5KCTx16XzB7BA6FU2bSN4ykI2+XZoMlYdSAXDS9W2XZBL4vazLLYl8ohJ/5/WmI=,iv:X/tLucsJCEtV6S2Lu8hodZZc4gRcSdhDx9DfRZD5NJo=,tag:ua3itiYLI3r9GFYWDem1RA==,type:str]
  pgp:
    - created_at: '2021-10-31T00:32:08Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0lsvhpSLVLLAQ/8DZJKJ+7i2ynBa7PheoKD8ZW4YSZlQ1bjXi8IQDb5W0KF
        MeC4bi91IvKF9DcztC+kFSJ+3Ao2NpSWMn0kGufz7QuncCyO2N+8x596gG3vRrQE
        KbHjgojaDi9kW6GQ04xCbamMzBxDJEnl0Xke3s4H2c473jgR4elBFmkPQPd+paei
        514mu6MxZ2Zb9Mk+Rn2tsFEUB9DnYLIt0vDZ60IU3ERqIeNM8mtzxUwvhNWbvuLi
        Fc5QBVUoAKScrXv3sBX5UKi0lyuZ9qGrC3OahGXYv9+gdmHbrvjjnaekotavoZ78
        GONJJPw7SkPr2ElIHBmP7GKw3G4Y1ruIJbOSyq9Bw8BMPVbZ8yshYwzWyNFb+D9B
        a/9dLg+Edrn+zQUzIdn1vr40xpmzlRk1Tp4ko6Z3eU2izfK4yGHkG/zV5d+Ni/fN
        dzJqagycW9m+PSOK5gm9KThp/lVeQmSuBOuNlq7uaMGfkWV/PLp9qtswqJuPeqXJ
        XnbsO70OAi3m41DrCjGCRsaBXHWUFyRSPaRZvGGYjsLH0Nmt25WvmMAktjQ+Yeqp
        l/97g6EckmOWAELNqC9JJ/plfwBzqau+D0hDzVDL71USjChuXKP39yEQ+Eyy95SZ
        Rx7kR8E1hdFp2TcNMWc94RDVfXRT7D1T3pMuKsQw/UJr3FMLJwkGIbSutDcRCvfS
        XgHHW0Q8OdXNiRJWh73ZULiXdJr4QySCqfsCXgUGNOv1aR/FWv4KQsGnBFMOmrTv
        i0+4rn+V3xdTY2c1CrN1+ahQSABrEVDFhmRyF6P2BukLzmO6mIxWPIOAaN/1Fmg=
        =nG8r
        -----END PGP MESSAGE-----
      fp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
