services:
  workouts:
    image: workouts:dev
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.app.dev
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - /home/node/app/node_modules
      - ../../:/home/node/app
    networks:
      - workouts-dev
    stop_signal: SIGKILL

  postgres:
    image: postgres:13.4
    env_file:
      - ../../.env.db.dev
    volumes:
      - /var/lib/postgresql/data
    networks:
      - workouts-dev

networks:
  workouts-dev:
