services:
  workouts:
    image: ericdang/workouts:dev
    ports:
      - "3000:3000"
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbUser=postgres
      - dbPassword=postgres
      - dbName=workouts
      - allowedHosts=http://localhost,https://dev.erickdang.com
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - node_modules:/home/node/app/node_modules
      - ../../:/home/node/app
    networks:
      - workouts-dev

  postgres:
    image: postgres:13.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workouts
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - workouts-dev

networks:
  workouts-dev:

volumes:
  node_modules:
  postgres:
