apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workouts
  namespace: default
spec:
  values:
    ingress:
      annotations:
        cert-manager.io/issuer: letsencrypt
        nginx.ingress.kubernetes.io/use-regex: "true"
      hosts:
      - host: dev.erickdang.com
        paths:
        - path: /api/v1/templates/
          pathType: Prefix
        - path: /api/v1/records/
          pathType: Prefix
        - path: /api/v1/types/
          pathType: Prefix
      tls:
      - hosts:
        - dev.erickdang.com
        secretName: letsencrypt-workouts
  postRenderers:
  - kustomize:
      images:
      - name: ericdang/workouts
        newName: ericdang/workouts
        newTag: dev-b03cb56b-1645480576 # {"$imagepolicy": "flux-system:workouts:tag"}
