apiVersion: v1
kind: Secret
metadata:
  name: workouts-secrets
  namespace: default
stringData:
  dbHost: ENC[AES256_GCM,data:5Q4coIGKcWFgC+XPNYi4mGvLzH8zoyV/dP7VRKNe70EgOvEVPBZ+,iv:lZn8oz9aiTfUvAWXbyB3Z1wLzTXC25U8o1uZRkIsaK8=,tag:bsZtKDCsdWMgv4ywJXfAVg==,type:str]
  dbPort: ENC[AES256_GCM,data:N+oQqQ==,iv:GROipWG+toJz9MXVuc7Ii7FjEVOVSaW5OMWWaUaRGg0=,tag:1m1gIbo7tgIiBVVAPwtsdQ==,type:str]
  dbUser: ENC[AES256_GCM,data:sN1m/QjPyURs9YiLOS25vf6Icgpt301Z4DVtetNvrxc=,iv:Jgvpd9NhKbYIvOvMx2Mr9AcO2Xi5284YXNtrwSTiKkY=,tag:GVHUPBR0RcHhO9S60yZWsA==,type:str]
  dbPassword: ENC[AES256_GCM,data:xzNU2sa5S4qAgw6pLhvRbBsCO70SRNqy1OXEhKdKEpU=,iv:okddX73KlLK77IGRU6B5/7gUjV80AbfKAKD96oCZ1Uc=,tag:+lKU2Vi+1bxouRMcFP1vEQ==,type:str]
  dbName: ENC[AES256_GCM,data:n5CzEZYv4bU=,iv:zDsJxadYWJaXkI9KLnOH3hzcz8+LlBftcDP+q7CFFC0=,tag:nqY5MgEn3sjx9kem72egCg==,type:str]
  httpPort: ENC[AES256_GCM,data:clT34g==,iv:x3Hl43zYKQR/4MfIaBsFoAhB1g7/AuQPANCv6mTUo5w=,tag:JVtWhTFmX8O+k0+gTJ9GNA==,type:int]
  accessTokenPublic: ENC[AES256_GCM,data:7qGMJVx6vTYNd4F+urj7x1ER6z84vE9SBqWgkKw/TF4lLhgyg2jJyD8QcFXLmINcAouD4bBZxDdE4H29kliGwKs/OaZh04HvGW02mG7ZnPUXb436mhpMTloAMERkABkelMoMxzCyer6bCpW2NCEQbtETIHFKtXJRuBdBS7r9SqAoAzZ4QM5w0MmEb9k30USTKiI=,iv:B83qAIWtYi2WF7GfuuFRIb3MzKf8LRyvFD+gpJIW9AM=,tag:BXP476MW0cE3JUEpWCMbsQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv:
    - vault_url: https://flux-dev-b4bcd66564.vault.azure.net
      name: workouts-sops
      version: 918470840b3d41fab3ccd866891cf973
      created_at: '2021-12-11T17:51:02Z'
      enc: R9xse3nyNqYPSjpzvWHXSQ-6fiBs3RGSKY43g4fcNgRPOme3_wVU2IM6sj2AauyN4ifGEOvS_YR6JSW0H1d0cWxWiefBrSgX6OTUqNaJTYNijQfJ86KOsLWaU_keAmttozPYjPY9BmXNqLqZMS7zpJFMSGrM-OGQ8VsnNNRT8jYRSWwI23RUVzKHNuCp4xHXdHlvnojmtcT2uTtiOeapAQfywHKbPtga7N_2WUx_fpqobWyG7HqVYqORnHKgZBxyPNN0rJJSAY2u8k6Q0dFIQS_hfJhE7WQcaId7IfVdWptXAhMkyZvZ_07Xvgiwh0Z8sC8uTPPvGV_cUOfeLcvYPQ
  hc_vault: []
  age: []
  lastmodified: '2021-12-11T17:51:05Z'
  mac: ENC[AES256_GCM,data:s8KNeqcyS9jE1HNivJiqeKzaYcQo/S8Sv/cHc+ZZYYCkV6SNVmG5wVwS489gC0KiIWy81HwyVRxJKlQkFBQf/tX4H7QhVHj9/nIp+hdtjJPi3dC94tm8Xatll4MdNmgH/+jqRvQBKYk7jqJsA5HFcGZ3DhB/z0St4/Q7zx8sru0=,iv:RWipethRQCwf6uyV9Q1zIZJWEdRiTqJWt+FeGkA0+mw=,tag:xKlHpdf37AEWhCOVsFu5Yw==,type:str]
  pgp:
    - created_at: '2021-12-11T17:51:02Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0lsvhpSLVLLAQ//VZ1mRtnadzRtC+lXuESV4ifZJg7izIsYp2AP6mD1Earb
        kJg2QLW3KKeh3ApUA5Ve0LbFmbPGk/6l3KroFpckQo1i8ygz130z/4DOXkUXKvaB
        a+HGG7jBwkW7YcGvvyH7dqWcmnJoHMfByOTjBr/VAYfCrjglV6obaFoMTo6S1BMO
        EHQIL7Hc7t2TdgCvrbTR3l2JSkEZp8qMnZfCRjOKjsan6RwLXKP5H5ny5+1ClmCd
        wm3YzLDGP4iCC2QFM88pV1i8blsWT+KRRwGoj2HODmI5CMpV+W9GZ5oIZRp5oxya
        L1haopC34xtBeUOdpJTFF6HG4HLLpKeR8Pzhbl6UB+rNZ62kIKXS3ZSz5dFk2ooQ
        JXJV+718gIkkfaUP4xYh4ECTeN/LhrmRKr29KnToaXUGI0FCe6umkj5jA8psVk8K
        HdzIQhC9rHnALRniL/l5pLWgIIviBaXL0gVjjB7k7CEwTCyCgWJTUJF13UhHetJC
        7hPWt/4p9rKuLO0neE40oK4Z3LtSEXSy4pq+hJ80dQvEYmVeEnnHjCECNz99r0nT
        VsRIYddaSKm/8AFxInJbIGJvXtxbqvXCkxGA/UmPvH5bvIMaqElGHOGQVgscwfFQ
        2m55voReW5nfRQcbkeLufxhHoXh5No9YKaSjueMJKTyIyNGhuOZZ6k4gY4VuNEbS
        XgEUUMMgSUoKp/V8eaRyxRy9Q3sUaDoCEZl6yaCh9iISWzhUOsv/fcocrB0TBeCN
        Nk4GbDXubsD+RVodpS/TYqVgz1VTyV/VN+ZO+8NKg3uSCic3Xtm1Bowu2M76UK0=
        =XjVs
        -----END PGP MESSAGE-----
      fp: A9D0E9EDCEA9201EA6214063FE9E4A501304255A
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
