services:
  auth:
    image: auth:prod
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.app.dev
    networks:
      - auth-prod

  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    env_file:
      - ../../.env.db.dev
    volumes:
      - /var/lib/postgresql/data
    networks:
      - auth-prod

networks:
  auth-prod:
