name: Auth

env:
  DOCKER_BUILDKIT: 1
  DIRECTORY: backend/auth

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/auth/**
      - .github/workflows/auth.yml
  push:
    paths:
      - backend/auth/**
      - .github/workflows/auth.yml
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3.1.0

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.DIRECTORY }}

      - name: Lint
        run: yarn lint
        working-directory: ${{ env.DIRECTORY }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build dev Docker image
        run: yarn build:dev
        working-directory: ${{ env.DIRECTORY }}

      - name: Export dev Docker image
        run: docker save auth:dev > /tmp/auth.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: auth
          path: /tmp/auth.tar

  unit-test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3.1.0

      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: auth
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/auth.tar

      - name: Unit test
        run: yarn test:unit
        working-directory: ${{ env.DIRECTORY }}

  integration-test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3.1.0

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.DIRECTORY }}

      - name: Setup environment
        run: yarn setup
        working-directory: ${{ env.DIRECTORY }}

      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: auth
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/auth.tar

      - name: Start test stack
        run: yarn up:test --wait
        working-directory: ${{ env.DIRECTORY }}

      - name: Run tests
        run: docker compose -p test-auth exec -T auth yarn jest __tests__/integration
        working-directory: ${{ env.DIRECTORY }}

  push-staging:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - lint
      - unit-test
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: tag
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=TAG::dev-${sha}-${ts}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DIRECTORY }}
          file: ${{ env.DIRECTORY }}/docker/prod/Dockerfile
          push: true
          tags: ericdang/auth:${{ steps.tag.outputs.TAG }}
