name: Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install SOPS
        uses: mdgreenwald/mozilla-sops-action@v1
        id: install
        with:
          version: latest

      - name: Install and Run Pre-commit
        uses: pre-commit/action@v2.0.3
