name: Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install SOPS
        uses: mdgreenwald/mozilla-sops-action@v1
        id: install
        with:
          version: latest

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.29.0

      - name: Install Terraform Docs
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | \
          grep -o -E "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && \
          tar xzf terraform-docs.tgz && \
          chmod +x terraform-docs && \
          sudo mv terraform-docs /usr/bin/

      - name: Install TFSec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/download/v0.47.0/tfsec-linux-amd64 && \
          chmod +x tfsec-linux-amd64 && \
          sudo mv tfsec-linux-amd64 /usr/bin/tfsec

      - name: Install and Run Pre-commit
        uses: pre-commit/action@v2.0.3
