name: Mobile

env:
  DIRECTORY: frontend/mobile

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/mobile/**
      - .github/workflows/mobile.yml
  push:
    paths:
      - frontend/mobile/**
      - .github/workflows/mobile.yml
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "17.1.x"

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.DIRECTORY }}

      - name: Lint
        run: yarn lint
        working-directory: ${{ env.DIRECTORY }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "17.1.x"

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.DIRECTORY }}

      - name: Run unit tests
        run: yarn test:unit
        working-directory: ${{ env.DIRECTORY }}
