name: Mobile

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/mobile/**
      - .github/workflows/mobile.yml
  push:
    branches:
      - main
    paths:
      - frontend/mobile/**
      - .github/workflows/mobile.yml
  workflow_dispatch:

jobs:
  test-whitebox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '17.1.x'

      - name: Install dependencies
        run: cd frontend/mobile && yarn install

      - name: Run unit tests
        run: cd frontend/mobile && yarn test:unit
